language: generic
sudo: required

services:
  - docker

before_install:
  - echo "Before installing"

install:
  - docker build -t sfarrell/cc7-basic .

script:
  - docker run sfarrell/cc7-basic echo "good container"

after_success:
  - echo "Success"

before_deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  - docker push sfarrell/cc7-basic
