language: generic
sudo: required

services:
  - docker

before_install:
  - echo "Before installing"

install:
  - travis_wait 50 docker build -t sfarrell/cc7-basic .

script:
  - docker run sfarrell/cc7-basic echo "good container"

after_success:
  - echo "Success"
